[programs.localnet]
check = "98ZZksmcbtKXafBzaRLzSrVWgvWZgkVkppr4P8cGrAXm"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/vecheslav/.config/solana/id.json"

[scripts]
test = "yarn test"
