name: Publish package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: yarn install --immutable
    - run: yarn build

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          scope: "@getcheck"
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn run publish --tag latest
        env:
          YARN_NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
